
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 07 01:09:13 CET 2020
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int DIVIDE = 23;
  public static final int LBRACKET = 41;
  public static final int CONST = 9;
  public static final int MINUS_MINUS = 35;
  public static final int NOT_EQUAL = 26;
  public static final int LPAREN = 39;
  public static final int GREATER = 27;
  public static final int CONTINUE = 10;
  public static final int NUM_CONST = 2;
  public static final int LESS = 29;
  public static final int FOR = 13;
  public static final int MINUS = 21;
  public static final int RPAREN = 40;
  public static final int SEMICOLON = 36;
  public static final int AND = 31;
  public static final int OR = 32;
  public static final int COMMA = 37;
  public static final int CLASS = 8;
  public static final int LESS_EQUAL = 30;
  public static final int PLUS = 20;
  public static final int MULTIPLY = 22;
  public static final int IF = 14;
  public static final int DOT = 38;
  public static final int ABSTRACT = 6;
  public static final int EOF = 0;
  public static final int RETURN = 19;
  public static final int PLUS_PLUS = 34;
  public static final int RBRACKET = 42;
  public static final int EQUAL = 33;
  public static final int GREATER_EQUAL = 28;
  public static final int NEW = 15;
  public static final int error = 1;
  public static final int MOD = 24;
  public static final int BREAK = 7;
  public static final int IDENT = 5;
  public static final int VOID = 45;
  public static final int LBRACE = 43;
  public static final int ELSE = 11;
  public static final int READ = 18;
  public static final int RBRACE = 44;
  public static final int EXTENDS = 12;
  public static final int PROG = 16;
  public static final int BOOL_CONST = 4;
  public static final int EQUAL_EQUAL = 25;
  public static final int PRINT = 17;
}

